pj3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from polls import views

app_name = 'polls'
urlpatterns = [
    path('',views.home_page,name='welcome'),
    path('home/', views.IndexView.as_view(), name='home'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_signup,name='signup'),
    path('logout/', views.user_logout,name='logout'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class Question(models.Model):
    question_text=models.CharField(max_length=700)
    pub_date=models.DateTimeField('Date published')

    def __str__(self):
        return self.question_text
    
    def published_recently(self): 
        now = timezone.now() 
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        published_recently.admin_order_field = 'pub_date'
        published_recently.boolean = True
        published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    choice_text=models.CharField(max_length=200)
    question=models.ForeignKey(Question, on_delete=models.CASCADE)
    votes=models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

polls/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class UserSignUp(UserCreationForm):
    password2=forms.CharField(label='Password (Again)', widget=forms.PasswordInput())
    password1=forms.CharField(label='Set Password', widget=forms.PasswordInput())
    class Meta:
        model=User
        fields=['username','email']
        labels={'email':'Email', 'username':'Set Username'}

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from polls.models import Question, Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from polls.forms import UserSignUp
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout

def home_page(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/home/')
    else:
        return render(request, 'polls/welcome.html')


# Index page after log in by user
class IndexView(generic.ListView): 
    template_name = 'polls/index.html' 
    context_object_name = 'latest_question_list' 
    def get_queryset(self): 
        """Return the last five published questions.""" 
        return Question.objects.filter( pub_date__lte=timezone.now() ).order_by('-pub_date')[:10]

# voting details view here
class DetailView(generic.DetailView): 
    model = Question 
    template_name = 'polls/detail.html' 
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

# results view here
class ResultsView(generic.DetailView): 
    model = Question 
    template_name = 'polls/result.html'

# To vote for desired option by user
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {'question': question,
        'error_message': "You didn't select a choice.",})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

# user login view here
def user_login(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            fm=AuthenticationForm(request=request,data=request.POST)
            if fm.is_valid():
                uname=fm.cleaned_data['username']
                upass=fm.cleaned_data['password']
                user=authenticate(username=uname,password=upass)
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect('/home/')
        else:
            fm=AuthenticationForm()
        return render(request, 'polls/login.html', {'form':fm})
    else:
        return HttpResponseRedirect('/login/')

# user logout view here
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/login/')

# sign up by user
def user_signup(request):
    if request.method=='POST':
        fm=UserSignUp(request.POST)
        if fm.is_valid():
            fm.save()
            messages.success(request, 'Account created successfully. Please Log in now.')
    else:
        fm=UserSignUp()
        messages.success(request, 'Sign Up for only New User')
    return render(request, 'polls/signup.html', {'form':fm})

polls/templates/polls/detail.html
{% extends 'parents.html' %}
{% load static %}
{% block title %} Detail Page{% endblock title %}
{% block scss %}  <link rel="stylesheet" href="{% static 'polls/css/detail.css' %}">{% endblock scss %}

{% block content %}
<div class="container mt-3">
<div class="p-3 mb-2 bg-secondary text-white">
<h4>Ques. {{ question.question_text }}</h4>
</div>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}"><h6>{{ choice.choice_text }}</h6></label><br>
{% endfor %}
<br>
<input class="btn btn-primary" type="submit" value="Vote">
</form>
</div>
{% endblock content %}

polls/templates/polls/index.html
{% extends 'parents.html' %}
{% load static %}
<title> {% block title %} Dashboard{% endblock title %} </title>
{% block scss %}  <link rel="stylesheet" href="{% static 'polls/css/index.css' %}">{% endblock scss %}

{% block content %}

<div class="container mt-3">
  {% if latest_question_list %}
            <ol>
            {% for question in latest_question_list %}
                <h5><li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li></h5> <br>
            {% endfor %}
            </ol>
        {% else %}
        <p>No polls are available.</p>
        {% endif %}
</div>

{% endblock content %}

polls/templates/polls/login.html
{% extends 'parents.html' %}
{% load static %}
{% block title %} User Login {% endblock title %}
{% block scss %} <link rel="stylesheet" href=" {% static 'polls/css/login.css' %}"> {% endblock scss %} 
{% block content %}

<div class="container cont">
 <div class="row mt-4 login">
    <form action="" method="POST"> 

    {% csrf_token %}
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %} <p> {{error}}</p> {% endfor %}
    {% endif %}

    {% for fm in form %}
    {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br> <br>
    {% endfor %}

    <input type="submit" class="btn btn-primary" value="Log In"> &nbsp &nbsp <h6> for New User <i class="far fa-hand-point-right"></i> </h6>
   <a href="{% url 'polls:signup' %} "> Sign Up</a>
    </form>
 </div>
</div>
{% endblock content %}

polls/templates/polls/result.html
{% extends 'parents.html' %}
{% load static %}
{% block title %} Result Page{% endblock title %}
{% block scss %}  <link rel="stylesheet" href="{% static 'polls/css/result.css' %}">{% endblock scss %}

{% block script %}
<script>
$(document).ready(function(){
var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: [{% for choice in question.choice_set.all %} '{{choice.choice_text}}', {% endfor %}],
            datasets: [{
                label: 'Maximun Votes',
                data: [{% for choice in question.choice_set.all %} {{choice.votes}}, {% endfor %}],
                borderColor:'Green',
                pointBackgroundColor:'blue',
                backgroundColor:'#73C6B6',
                pointRotaion:3,
                pointRadius:5,
                borderWidth: 2,
            }]
        },
        options:{
            responsive:false,
            layout: {padding:{left:100, top:10, bottom:100}},
            tooltips: {enabled:false},
            title: {display:true, text: 'Top Treding Data Visualization', fontSize:25,},
            animation: {duration:3900, easing:'easeInOutSine'}
        },
    });
});
</script>
{% endblock script %}

{% block content %}

<div class="container mt-3">
<h3>{{ question.question_text }}</h3>
<ul>
{% for choice in question.choice_set.all %}
    <li><h5>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</h5></li>
{% endfor %}
</ul>
<h5><a href="{% url 'polls:home' %}">Vote again?</a></h5>
<canvas id="myChart" width="700" height="501"></canvas>
</div>
{% endblock content %}

polls/templates/polls/signup.html
{% extends 'parents.html' %}
{% load static %}
{% block title %} User Registration {% endblock title %}
{% block scss %} <link rel="stylesheet" href=" {% static 'polls/css/signup.css' %}"> {% endblock scss %}
{% block content %}

<div class="container">
 
    <div class="row mt-5 cont">
    <form action="" method="post"> {% csrf_token %}

    {% for fm in form %}
        <p>{{fm.label_tag}} {{fm}} {{fm.errors|striptags}}</p> <br>
    {% endfor %}
    <input type="submit" class="btn btn-primary" value="Submit"> &nbsp &nbsp
    <a href=" {% url 'polls:login' %}"> Log In</a>
    </form>
    
    {% if messages %}
    {% for message in messages %}
    <small {% if message.tags %} {{message.tags}} {% endif %} >{{message}} </small>
    {% endfor %}
    {% endif %}
   
    </div>
</div>

{% endblock content %}

polls/templates/polls/welcome.html
{% extends 'parents.html' %}
{% load static %}
<title> {% block title %} Welcome Page{% endblock title %} </title>
{% block scss %}  <link rel="stylesheet" href="{% static 'polls/css/welcome.css' %}">{% endblock scss %}

{% block content %}
<div class="container mt-3">
  <div class="row">
    <h3>In this digital world can we imagine our lives without computers?</h3>
    <div class="col-5">
    <p class="para">
    </p>With the world becoming more and more digital, the scope for Computer Science is on the rise. 
    Developed countries pride themselves on having one of the highest technical human power in the world. The IT/CS 
    sector is increasing rapidly in the world since the 20th century. Today's everyone should be familiar 
    with all the basic computer skills to perform better while working. India has become the digital 
    hub globally at around 75% of the world.<br><br>Learning and enhancing your skills are vital in this technological era. 
    It helps you to prepare yourself for getting the highest paying jobs in the field of your choice. 
    And if you are a professional already, learning new technologies and tools will take you an inch 
    closer to the promotion you always dreamt it. Hence, it is necessary to know what's trending things 
    are at the top in the world. That's why I have a voting survey for you. Before going to the voting 
    survey, you have to log in here. <a href="{% url 'polls:login' %}">
    <h6><i class="far fa-hand-point-right"></i> &nbsp Log In</h6>
    </a>
    </div>
    <div class="col-5 contpic">
    <img class="pics" src="{% static 'polls/images/pic3.jpeg' %}" alt="globally digital">
    </div>
  </div>
</div>

{% endblock content %}

templates/parents.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock title %} </title>
    <link rel="stylesheet" href=" {% static 'polls/css/bootstrap.css' %} ">
    <link rel="stylesheet" href=" {% static 'polls/css/all.css' %} ">
    {% block scss %}  
      <link rel="stylesheet" href=" {% static '' %} "> 
      {% endblock scss %}
    <script src=" {% static 'polls/js/bootstrap.js' %} "></script>
    <script src=" {% static 'polls/js/popper.js' %} "></script>
    <script src=" {% static 'polls/js/jquery.js' %} "></script>
    <script src=" {% static 'polls/js/all.js' %} "></script>
    <script src="{% static 'polls/js/chart.js' %} "></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item"><a class="nav-link" href=" {% url 'polls:welcome' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li class="nav-item"><a class="nav-link" href="{% url 'polls:home' %} "> Survey Dashboard</a> </li>
    <li class="nav-item"><a class="nav-link" href="{% url 'polls:logout' %} "> Log Out</a></li>
    {% else %}
    <li class="nav-item"><a class="nav-link" href="{% url 'polls:login' %} "> Log In</a></li>
    {% endif %}
    </ul>
  </div>
</nav>

  {% block script %}
  {% endblock script %}

  {% block content %}

  {% endblock content %}

</body>
</html>